language: node_js
sudo: required
node_js:
  - "lts/*"
install:
  - npm install -g vuepress
script:
  - npm run build && cd .vuepress/dist
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: .vuepress/dist