language: node_js
sudo: required
node_js:
  - "lts/*"
branches:
  only:
  - master

cache:
  directories:
  - node_modules
  yarn: true

script:
  - ./deploy.sh

install:
  - yarn

before_install:
  - chmod +x deploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./sources/.vuepress/dist/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master