language: node_js
sudo: required
node_js:
  - "lts/*"

install:
  - npm install -g vuepress
script:
  - vuepress build && cd .vuepress/dist
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $REPO_TOKEN
  on:
    branch: master
  local-dir: .vuepress/dist